apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-nodejs-app-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: nginx-nodejs-app
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 5s
  idleReplicaCount: 0
  triggers:
    - type: external
      metadata:
        scalerAddress: http://34.118.231.175:80
